const {test,before,after,beforeEach}=require('node:test');
const {initializeTestEnvironment,assertFails,assertSucceeds}=require('@firebase/rules-unit-testing');
const {doc,getDoc,setDoc,updateDoc,deleteDoc}=require('firebase/firestore');const fs=require('node:fs');
let env;before(async()=>{env=await initializeTestEnvironment({projectId:'demo-egygrillz',firestore:{rules:fs.readFileSync('firestore.rules','utf8'),host:'127.0.0.1',port:8080}});});
after(async()=>{await env?.cleanup();});
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,'_admins/owner'),{active:true,minAuthTime:0});for(const path of ['appointments/a','clients/a','messages/a','settings/schedule','schedule/a','golds/a','_pushDevices/a'])await setDoc(doc(db,path),{name:'test',phone:'+201234567890'});});});
test('anonymous clients cannot read, create, edit or delete private records',async()=>{const db=env.unauthenticatedContext().firestore();for(const path of ['appointments/a','clients/a','messages/a','settings/schedule','schedule/a','_pushDevices/a']){await assertFails(getDoc(doc(db,path)));await assertFails(setDoc(doc(db,path),{name:'bad'}));await assertFails(deleteDoc(doc(db,path)));}});
test('signed-in account without admin claim is not privileged',async()=>{const db=env.authenticatedContext('ordinary').firestore();await assertFails(getDoc(doc(db,'clients/a')));await assertFails(setDoc(doc(db,'settings/schedule'),{}));await assertFails(getDoc(doc(db,'appointments/a')));});
test('admin reads private data, manages clients and schedule, but cannot bypass booking backend',async()=>{const db=env.authenticatedContext('owner',{admin:true,auth_time:Math.floor(Date.now()/1000)}).firestore();for(const p of ['clients/a','appointments/a','messages/a','settings/schedule'])await assertSucceeds(getDoc(doc(db,p)));await assertSucceeds(updateDoc(doc(db,'clients/a'),{name:'changed'}));await assertSucceeds(setDoc(doc(db,'settings/schedule'),{openDays:[1],openHour:16,closeHour:22,slotDuration:60,holidays:[]}));await assertSucceeds(updateDoc(doc(db,'messages/a'),{read:true}));await assertFails(setDoc(doc(db,'appointments/new'),{}));await assertFails(updateDoc(doc(db,'appointments/a'),{status:'cancelled'}));await assertFails(deleteDoc(doc(db,'appointments/a')));await assertFails(setDoc(doc(db,'messages/new'),{}));});
test('catalog is public read-only and server collections are denied even to admins',async()=>{for(const ctx of [env.unauthenticatedContext(),env.authenticatedContext('owner',{admin:true,auth_time:Math.floor(Date.now()/1000)})]){const db=ctx.firestore();await assertSucceeds(getDoc(doc(db,'golds/a')));await assertFails(setDoc(doc(db,'golds/new'),{}));await assertFails(getDoc(doc(db,'_pushDevices/a')));await assertFails(setDoc(doc(db,'_audit/a'),{}));await assertFails(getDoc(doc(db,'unknown/a')));}});

test('removing active membership invalidates an existing admin token',async()=>{const db=env.authenticatedContext('owner',{admin:true,auth_time:Math.floor(Date.now()/1000)}).firestore();await assertSucceeds(getDoc(doc(db,'clients/a')));await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'_admins/owner'),{active:false,minAuthTime:0});});await assertFails(getDoc(doc(db,'clients/a')));});
