/* Production studio UI. No fixtures, demo switch or authorization bypass. */
(async()=>{
 const $=id=>document.getElementById(id),auth=firebase.auth(),db=firebase.firestore();
 let rows=[],unsubscribe,activeUid=null,filter='today',cursor=null,previous=[],lastDoc=null,epoch=0,editorRow=null,createId=null,resolver=null,enrollmentSecret=null;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;};
 const notice=text=>{$('notice').textContent=text;};
 const day=()=>egyCairoNow().date;
 const persistence=auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);
 function clear(){enrollmentSecret=null;$('enrollment-secret').textContent='';$('enrollment-code').value='';$('enrollment').hidden=true;if($('booking-editor').open)$('booking-editor').close();++epoch;unsubscribe?.();rows=[];activeUid=null;$('bookings').replaceChildren();$('workspace').hidden=true;$('security').hidden=true;$('login').hidden=false;for(const id of ['stat-today','stat-upcoming','stat-arrived'])$(id).textContent='—';}
 function deny(reason){clear();$('connection').textContent='Not connected';if(reason!=='signed-out')notice(({expired:'Your session expired. Sign in again.',mfa:'Sign out and sign in with your authenticator.',revoked:'This account is not currently authorized.',unavailable:'Unable to verify access. Check your connection.','not-admin':'This account is not a studio admin.'})[reason]||'Sign in again.');}
 $('date-label').textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Cairo',weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase();
 function render(){
  const search=$('search').value.trim().toLowerCase(),list=rows.filter(a=>[a.name,a.phone,a.service].some(x=>String(x||'').toLowerCase().includes(search)));
  $('result-count').textContent=`${list.length} of ${rows.length} on this page · all times Africa/Cairo`;$('bookings').replaceChildren();
  if(!list.length)$('bookings').append(el('div','No matching appointments on this page.','empty'));
  for(const a of list){
   const card=el('article',undefined,'booking'),top=el('div',undefined,'booking-top'),time=el('div',a.time||'—','time');time.append(el('small',a.date));
   const client=el('div',undefined,'client');client.append(el('h3',a.name||'Unnamed client'),el('p',a.service||'Appointment'));
   top.append(time,client,el('span',a.status==='cancelled'?'Cancelled':a.showedUp===true?'Arrived':a.showedUp===false?'No show':a.status==='pending'?'Pending':'Confirmed','badge'));card.append(top);
   if(a.notes)card.append(el('p',a.notes,'small muted'));
   const actions=el('div',undefined,'actions'),phone=String(a.phone||'').replace(/[^\d+]/g,'');
   if(phone){const call=el('a','Call client');call.href='tel:'+phone;actions.append(call);let digits=phone.replace(/\D/g,'');if(/^01\d{9}$/.test(digits))digits='20'+digits.slice(1);if(digits.startsWith('00'))digits=digits.slice(2);const wa=el('a','WhatsApp ↗');wa.href='https://wa.me/'+digits;wa.target='_blank';wa.rel='noopener noreferrer';actions.append(wa);}
   const edit=el('button','Edit');edit.onclick=()=>openEditor(a);actions.append(edit);
   if(a.status!=='cancelled')for(const [label,data]of [['Confirm',{status:'confirmed'}],['Arrived',{showedUp:true}],['No show',{showedUp:false}],['Cancel',{status:'cancelled'}]]){
    if(label==='Confirm'&&a.status!=='pending')continue;const button=el('button',label);
    button.onclick=async()=>{if(label==='Cancel'&&!confirm('Cancel this booking and release its time slot?'))return;button.disabled=true;try{await egyCall('appointmentAdmin',{mode:'update',id:a.id,version:a.version||0,data});notice('Appointment updated.');await summary();}catch(e){notice(e.message);}finally{button.disabled=false;}};actions.append(button);
   }
   card.append(actions);$('bookings').append(card);
  }
  $('previous-page').disabled=!previous.length;$('next-page').disabled=rows.length<50;
 }
 function subscribe(){
  unsubscribe?.();const serial=++epoch;rows=[];render();$('connection').textContent='Connecting…';
  let q=db.collection('appointments');if(filter==='today')q=q.where('date','==',day());if(filter==='upcoming')q=q.where('date','>',day());
  q=q.orderBy('date',filter==='all'?'desc':'asc').orderBy(firebase.firestore.FieldPath.documentId(),filter==='all'?'desc':'asc');if(cursor)q=q.startAfter(cursor.date,cursor.id);
  unsubscribe=q.limit(50).onSnapshot({includeMetadataChanges:true},snap=>{if(serial!==epoch)return;rows=snap.docs.map(d=>({...d.data(),id:d.id}));lastDoc=rows.at(-1);render();$('connection').textContent=snap.metadata.fromCache?'Reconnecting · cached view':'Live · secure connection';},()=>{if(serial!==epoch)return;rows=[];render();$('connection').textContent='Unavailable';notice('Cannot load appointments. Check your account permissions, connection and indexes.');});
 }
 async function summary(){const uid=activeUid;if(!uid)return;try{const s=await egyCall('adminSummary');if(uid!==activeUid)return;for(const [id,key]of [['stat-today','today'],['stat-upcoming','upcoming'],['stat-arrived','arrived']])$(id).textContent=s[key];}catch(e){notice(e.message);}}
 function openEditor(a){$('editor-error').textContent='';editorRow=a||null;createId=egyRequestId();for(const key of ['name','phone','email','service','notes','date'])$('edit-'+key).value=a?.[key]||'';if(!a)$('edit-date').value=day();let t='16:00';if(a?.time){const m=/^(\d+):(\d+) (AM|PM)$/.exec(a.time);if(m)t=String(Number(m[1])%12+(m[3]==='PM'?12:0)).padStart(2,'0')+':'+m[2];}$('edit-time').value=t;$('edit-status').value=a?.status||'confirmed';$('editor-title').textContent=a?'Edit appointment':'New appointment';$('booking-editor').showModal();}
 $('new-booking').onclick=()=>openEditor();$('close-editor').onclick=()=>$('booking-editor').close();
 $('booking-form').onsubmit=async e=>{e.preventDefault();const button=$('save-booking');button.disabled=true;const data={};for(const key of ['name','phone','email','service','notes','date','status'])data[key]=$('edit-'+key).value.trim();const [h,m]=$('edit-time').value.split(':').map(Number);data.time=String(h%12||12).padStart(2,'0')+':'+String(m).padStart(2,'0')+' '+(h>=12?'PM':'AM');
  try{await egyCall('appointmentAdmin',editorRow?{mode:'update',id:editorRow.id,version:editorRow.version||0,data}:{mode:'create',requestId:createId,data});$('booking-editor').close();notice('Saved securely.');await summary();}catch(e){$('editor-error').textContent=e.message;}finally{button.disabled=false;}};
 for(const button of document.querySelectorAll('[data-filter]'))button.onclick=()=>{filter=button.dataset.filter;cursor=null;previous=[];document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('selected',b===button));subscribe();};
 $('search').oninput=render;$('previous-page').onclick=()=>{cursor=previous.pop();subscribe();};$('next-page').onclick=()=>{if(!lastDoc)return;previous.push(cursor);cursor={date:lastDoc.date,id:lastDoc.id};subscribe();};$('refresh-board').onclick=()=>{subscribe();summary();};
 $('login-form').onsubmit=async e=>{e.preventDefault();$('sign-in').disabled=true;try{await persistence;await auth.signInWithEmailAndPassword($('email').value.trim(),$('password').value);$('password').value='';notice('');}catch(e){if(e.code==='auth/multi-factor-auth-required'){resolver=egyMfa.getMultiFactorResolver(egyMfa.getAuth(),e);$('mfa-form').hidden=false;notice('Enter your authenticator code.');}else notice('Sign-in failed. Check your details or try again later.');}finally{$('sign-in').disabled=false;}};
 $('mfa-form').onsubmit=async e=>{e.preventDefault();const hint=resolver?.hints.find(h=>h.factorId==='totp');if(!hint){notice('This account needs a supported TOTP authenticator.');return;}try{await resolver.resolveSignIn(egyMfa.TotpMultiFactorGenerator.assertionForSignIn(hint.uid,$('mfa-code').value.trim()));$('mfa-code').value='';$('password').value='';$('mfa-form').hidden=true;resolver=null;}catch{notice('Verification failed. Check the current authenticator code.');}};
 $('reset').onclick=async()=>{try{await auth.sendPasswordResetEmail($('email').value.trim());notice('If eligible, a password reset email will be sent.');}catch{notice('Check the email and try again later.');}};
 const swPromise='serviceWorker'in navigator?navigator.serviceWorker.register('admin-sw.js',{scope:'./'}):Promise.resolve(null);swPromise.catch(()=>notice('Notifications require HTTPS and a supported browser.'));
 async function registerPush(){if(!await firebase.messaging.isSupported())throw Error('On iPhone, use iOS 16.4+ and open the installed Home Screen app.');if(EGY_CONFIG.vapidKey.startsWith('REPLACE_'))throw Error('Web Push configuration is missing.');const m=firebase.messaging(),token=await m.getToken({vapidKey:EGY_CONFIG.vapidKey,serviceWorkerRegistration:await swPromise});if(!token)throw Error('No push token issued.');await egyCall('pushDevice',{token});$('push-state').textContent='Enabled on this device.';}
 $('enable-push').onclick=async()=>{const button=$('enable-push');button.disabled=true;try{if(!('Notification'in window))throw Error('Install the Home Screen app first.');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Notifications not allowed. Change permission in device settings to enable them.');await registerPush();}catch(e){notice(e.message);}finally{button.disabled=false;}};
 $('disable-push').onclick=async()=>{try{await egyRemovePush();$('push-state').textContent='Disabled on this device.';}catch(e){notice(e.message);}};
 $('sign-out').onclick=async()=>{clear();await egySignOut();};
 $('enroll-mfa').onclick=async()=>{try{const password=prompt('Re-enter your admin password to set up an authenticator.');if(!password)return;const user=egyMfa.getAuth().currentUser;await egyMfa.reauthenticateWithCredential(user,egyMfa.EmailAuthProvider.credential(user.email,password));const session=await egyMfa.multiFactor(user).getSession();enrollmentSecret=await egyMfa.TotpMultiFactorGenerator.generateSecret(session);$('enrollment-secret').textContent=enrollmentSecret.secretKey;$('enrollment').hidden=false;}catch(e){notice('Authenticator setup failed. Enable TOTP in Firebase Authentication with Identity Platform, then try again.');}};
 $('finish-enrollment').onclick=async()=>{if(!enrollmentSecret)return;try{await egyMfa.multiFactor(egyMfa.getAuth().currentUser).enroll(egyMfa.TotpMultiFactorGenerator.assertionForEnrollment(enrollmentSecret,$('enrollment-code').value.trim()),'Studio authenticator');enrollmentSecret=null;$('enrollment-secret').textContent='';$('enrollment-code').value='';$('enrollment').hidden=true;notice('Authenticator enrolled. Your project owner can now require MFA for this account.');}catch{notice('Enrollment failed. Check the code and try again.');}};
 $('load-alerts').onclick=async()=>{try{const {jobs}=await egyCall('notificationAdmin',{action:'list'});$('delivery-alerts').replaceChildren();if(!jobs.length)$('delivery-alerts').append(el('p','No exhausted delivery jobs.','small muted'));for(const job of jobs){const row=el('p',job.channel+' · '+job.error+' '),button=el('button','Retry delivery');button.onclick=async()=>{button.disabled=true;try{await egyCall('notificationAdmin',{action:'retry',id:job.id});row.textContent='Queued for retry.';}catch(e){notice(e.message);button.disabled=false;}};row.append(button);$('delivery-alerts').append(row);}}catch(e){notice(e.message);}};
 egyWatchAdmin(async user=>{if(activeUid===user.uid)return;clear();activeUid=user.uid;$('login').hidden=true;$('workspace').hidden=false;$('security').hidden=false;subscribe();summary();if('Notification'in window&&Notification.permission==='granted')registerPush().catch(()=>{});},deny);
 window.addEventListener('offline',()=>{$('connection').textContent='Offline · changes unavailable';});window.addEventListener('online',()=>{if(activeUid){subscribe();summary();}});
 let lastDay=day();setInterval(()=>{if(!activeUid)return;if(lastDay!==day()){lastDay=day();cursor=null;previous=[];subscribe();}summary();},120000);
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&activeUid)summary();});
 try{if(await firebase.messaging.isSupported())firebase.messaging().onMessage(()=>{notice('A new booking has arrived.');summary();});}catch{/* Browsers without push retain full studio functionality. */}
})();
